### ISSUE TITLE
Missing setting enforce mode

### ISSUE THREAD

**Issue by JvdW** [thias/puppet-selinux#5]
I'm missing the possibility to set/clear SELinux state (/etc/selinux/config).
The puppet module of spiette has this functionality and it looks like its all in one class and should be easy to add to your puppet module.
Would you consider this an enhancement? and if yes do it yourself or should I try to submit a PR (That would be my second PR for a github project so it might take a few cycles to get it correct)

Joop

**Comment by thias** [comment]
FWIW, I'm an "SELinux should always be enforcing" person, so it's not a feature that I'm particularly interested in adding to my module. The whole point of my module is to be able to whitelist SELinux denials as well as update filesystem paths so that their context matches their content.

Knowing this, if it's simple and non-invasive, I'd be willing to include it, sure. Your call now :-)
